# Generated by CodiumAI

import pytest


class TestNextLive:

    # Prints "change in momentum - buy" when RSI crosses below the lower bound
    def test_rsi_crosses_below_lower_bound(self):
        import io
        import sys

        from backtesting import Backtest
        from backtesting.test import GOOG

        # Capture the output
        captured_output = io.StringIO()
        sys.stdout = captured_output

        class TestStrategy(RSIOscillatorCross):
            def next_live(self):
                super().next_live()

        bt = Backtest(GOOG, TestStrategy, cash=10_000, commission=0.002)
        bt.run()

        # Reset redirect.
        sys.stdout = sys.__stdout__

        # Check if the expected output is in the captured output
        assert "change in momentum - buy" in captured_output.getvalue()

    # Handles cases where RSI values are exactly at the upper or lower bound
    def test_rsi_at_bounds(self):
        import io
        import sys

        from backtesting import Backtest
        from backtesting.test import GOOG

        # Capture the output
        captured_output = io.StringIO()
        sys.stdout = captured_output

        class TestStrategy(RSIOscillatorCross):
            def next_live(self):
                super().next_live()

        bt = Backtest(GOOG, TestStrategy, cash=10_000, commission=0.002)
        bt.run()

        # Reset redirect.
        sys.stdout = sys.__stdout__

        # Check if the expected output is in the captured output
        assert "change in momentum - buy" not in captured_output.getvalue()
        assert "change in momentum - sell" not in captured_output.getvalue()
