#!/usr/bin/env python3
import argparse

import config
import technical_analysis


def main():
    parser = argparse.ArgumentParser(description="Process stock symbol and strategy.")
    parser.add_argument(
        "-s",
        "--symbol",
        required=True,
        nargs="+",
        help="The stock symbols to process (space-separated list)",
    )
    parser.add_argument("-st", "--strategy", help="The strategy to use (optional)")
    parser.add_argument(
        "-hg",
        "--hide_graphs",
        action="store_true",
        help="Hide graphs (optional, defaults to False)",
    )

    args = parser.parse_args()

    symbols = args.symbol
    strategy = args.strategy
    hide_graphs = args.hide_graphs

    if not strategy:
        strategy = config.DEFAULT_STRATEGY

    technical_analysis.analyze(symbols, strategy, hide_graphs)


if __name__ == "__main__":
    main()
