strategy_flow:
  #- optimization
  - live
stocks:
  - AAPL
  - MSFT
  - GOOG
  - QCOM
  - AMD
  - AVGO
  - NVDA
display_dashboard: true
save_reference: true
strategies: RSI
enable_optimizing: true
email_alerts:
  enabled: true
  recipients:
    - "example@gmail.com"