run_commands:
  - fetch_stocks
  - run_strategy
  - schedule_email
stocks:
  - AAPL
  - MSFT
  - GOOG
strategies:
  - name: moving_average
    parameters:
      window_size: 50
  - name: linear_regression
    parameters:
      lookback_period: 30
email_alerts:
  enabled: true
  frequency: daily
  recipients:
    - "example1@example.com"
    - "example2@example.com"
