strategy_flow:
  - optimization
  #- live
stocks:
  - AAPL
  - MSFT
  - GOOG
  - QCOM
  - AMD
  - AVGO
  - NVDA
  - TSLA
  #- NFLX
  #- SMCI
  #- LLY
display_dashboard: true
save_reference: false
strategies: RSI
enable_optimizing: false
enable_opt_portfolio: false
email_alerts:
  enabled: true
  recipients:
    - "example@gmail.com"