run_commands:
  - fetch_stocks
  - run_strategy
  # - email_alerts
stocks:
  - AAPL
  - MSFT
  - GOOG
show_graphs: true
show_feqos: true
save_reference: false
strategies:
  - name: technical_analysis
email_alerts:
  enabled: true
  recipients:
    - "example@gmail.com"
