strategy_flow:
  - optimization
  #- live
stocks:
  - AAPL
  - MSFT
  - GOOG
  - QCOM
  - AMD
  - AVGO
  - NVDA
  - TSLA
  - NFLX
display_dashboard: true
save_reference: false
strategies: Logistic
enable_optimizing: false
email_alerts:
  enabled: true
  recipients:
    - "example@gmail.com"