run_commands:
  - fetch_stocks
  - run_strategy
stocks:
  - AAPL
  - MSFT
  - GOOG
hide_graphs: true
strategies:
  - name: technical_analysis
email_alerts:
  enabled: true
  frequency: daily
  recipients:
    - "example1@example.com"
    - "example2@example.com"
